version: "3.9"
   
services:
  nginx:
    restart: always
    image: nginx:latest
    expose:
      - 8080
    ports:
      - "80:8080"
    volumes:
        - ./html:/srv/www/html
        - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
        - api
  api:
    restart: always
    build: .
    volumes:
      - .:/srv/www/isart2
    expose:
      - 8000
    ports:
      - "8000:8000"
    #command: python manage.py runserver 0.0.0.0:8000

